version: '3'

services:
 
 mariadb:
  container_name: mariadb
  image: mariadb
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
   args:
        - MYSQL_DB=${MYSQL_DATABASE}
        - MYSQL_U=${MYSQL_USER}
        - MYSQL_P=${MYSQL_PASSWORD}
      #  - MYSQL_RP=${MYSQL_ROOT_PASSWORD}
  env_file: .env
  volumes:
   - database:/var/lib/mysql
  networks:
   - inception
  expose:
   - "3306"
  restart: unless-stopped

 nginx:
  container_name: nginx
  image: nginx
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  depends_on: 
   - wordpress
  env_file: .env
  ports: 
   - "443:443"
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - inception
  # restart: on-failure

 wordpress:
  container_name: wordpress
  image: wordpress
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
   # args:
     #   - MYSQL_DB=${MYSQL_DATABASE}
     #   - MYSQL_U=${MYSQL_USER}
     #   - MYSQL_P=${MYSQL_PASSWORD}
  env_file: .env
  depends_on:
   - mariadb
  expose: 
   - "9000"
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - inception
  # restart: on-failure

volumes:
 wordpress:
  name: wordpress
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/rmamison/data/wordpress'
 database:
  name: database
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/rmamison/data/database'


networks:
  inception:
   driver: bridge
